language: python
python:
  - "3.6"
install:
  - pip install awscli
  - pip install tox
  - pip install ConfigParser
script:
  - tox
deploy:
  - provider: script
    script: python scripts/deploy_orchestration.py master ${AWS_LAMBDA_ROLE}
    on:
      branch: master
  - provider: script
    script: python scripts/deploy_orchestration.py develop ${AWS_LAMBDA_ROLE}
    on:
      branch: develop