language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - tox
deploy:
  provider: lambda
  access_key_id: ${AWS_ACCESS_KEY}
  secret_access_key: ${AWS_SECRET_KEY}
  function_name: "webscrape-lyrics"
  region: "us-east-1"
  role: ${AWS_LAMBDA_ROLE}
  runtime: "python3.6"
  handler_name: "handler"
